<?php
declare(strict_types=1);

return [
    'paths' => [
        'template_dir' => app_first_existing_path(
            app_join_path(app_root(), 'resources', 'cxp', 'repuestos_tytserv', 'templates'),
            app_join_path(app_root(), 'outputs', 'EJEMPLOAMANOTAREA3')
        ),
        // Ruta productiva actual del modulo web.
        // run_repuestos_tytserv.ps1 queda como fallback/manual probe verificado aparte.
        'script_path' => app_join_path(app_root(), 'scripts', 'cxp', 'repuestos_tytserv', 'process.js'),
    ],
    'module' => [
        'window_slug' => 'facturacion_repuestos_tytserv',
        'template_file' => 'FACTURACION REPUESTOS TYTSERV FEBRERO 2026.xlsx',
        'accepted_extensions' => ['xls', 'xlsx'],
        'file_fields' => [
            [
                'field' => 'excel_tyt',
                'label' => 'RepLibroVentasGeneral',
                'script_flag' => '-InputTyt',
                'brand_key' => 'tyt',
                'brand_label' => 'MATRIZ',
                'source_label' => 'Ventas',
                'summary_key' => 'tyt',
                'summary_label' => 'MATRIZ',
            ],
            [
                'field' => 'excel_nc_tyt',
                'label' => 'RepLibroDevolucionesGeneral',
                'script_flag' => '-InputNcTyt',
                'brand_key' => 'tyt',
                'brand_label' => 'MATRIZ',
                'source_label' => 'Devoluciones',
            ],
            [
                'field' => 'excel_peug',
                'label' => 'RepLibroVentasGeneral',
                'script_flag' => '-InputPeug',
                'brand_key' => 'peug',
                'brand_label' => 'PEUGEOT',
                'source_label' => 'Ventas',
                'summary_key' => 'peug',
                'summary_label' => 'PEUGEOT',
            ],
            [
                'field' => 'excel_nc_peug',
                'label' => 'RepLibroDevolucionesGeneral',
                'script_flag' => '-InputNcPeug',
                'brand_key' => 'peug',
                'brand_label' => 'PEUGEOT',
                'source_label' => 'Devoluciones',
            ],
            [
                'field' => 'excel_chgn',
                'label' => 'RepLibroVentasGeneral',
                'script_flag' => '-InputChgn',
                'brand_key' => 'chgn',
                'brand_label' => 'CHANGAN',
                'source_label' => 'Ventas',
                'summary_key' => 'chgn',
                'summary_label' => 'CHANGAN',
            ],
            [
                'field' => 'excel_nc_chgn',
                'label' => 'RepLibroDevolucionesGeneral',
                'script_flag' => '-InputNcChgn',
                'brand_key' => 'chgn',
                'brand_label' => 'CHANGAN',
                'source_label' => 'Devoluciones',
            ],
            [
                'field' => 'excel_szk',
                'label' => 'RepLibroVentasGeneral',
                'script_flag' => '-InputSzk',
                'brand_key' => 'szk',
                'brand_label' => 'SUZUKI',
                'source_label' => 'Ventas',
                'summary_key' => 'szk',
                'summary_label' => 'SUZUKI',
            ],
            [
                'field' => 'excel_nc_szk',
                'label' => 'RepLibroDevolucionesGeneral',
                'script_flag' => '-InputNcSzk',
                'brand_key' => 'szk',
                'brand_label' => 'SUZUKI',
                'source_label' => 'Devoluciones',
            ],
        ],
        'page' => [
            'top_note' => 'Carga y procesamiento mensual por 4 marcas',
            'hero_chip' => 'Flujo mensual',
            'hero_lead' => 'Carga por cada marca el archivo de ventas y el de devoluciones para generar la salida final en el formato de la plantilla manual.',
            'hero_note' => 'Salida: un archivo .xlsx listo para descarga.',
            'inputs_title' => 'Entradas requeridas',
            'retention_tag' => 'Retencion',
            'retention_description' => 'Se elimina automaticamente lo mas antiguo.',
            'process_title' => 'Procesar plantilla',
            'process_description' => 'Sube los 8 archivos del mes: 4 RepLibroVentasGeneral y 4 RepLibroDevolucionesGeneral.',
            'button_label' => 'Procesar y generar reporte',
            'output_tag' => 'Salida',
            'output_title' => 'storage/outputs',
            'output_description' => 'Prefijo de archivos: repuestos_tytserv_',
            'history_title' => 'Historial reciente',
            'history_empty_title' => 'No hay reportes generados aun.',
            'history_empty_description' => 'La primera ejecucion aparecera aqui.',
        ],
    ],
];
