<?php

declare(strict_types=1);

$legacyRoot = env('LEGACY_APP_ROOT', dirname(__DIR__, 2));
$legacyBaseUrl = rtrim((string) env('LEGACY_PUBLIC_BASE_URL', 'http://localhost/SOFTWARECONTABILIDAD'), '/');
$accionesRoot = $legacyRoot . DIRECTORY_SEPARATOR . 'resources' . DIRECTORY_SEPARATOR . 'cxp' . DIRECTORY_SEPARATOR . 'acciones';
$accionesTemplates = $accionesRoot . DIRECTORY_SEPARATOR . 'templates';
$serviciosRoot = $legacyRoot . DIRECTORY_SEPARATOR . 'resources' . DIRECTORY_SEPARATOR . 'cxp' . DIRECTORY_SEPARATOR . 'servicios_marcas';
$serviciosTemplates = $serviciosRoot . DIRECTORY_SEPARATOR . 'templates';
$repuestosRoot = $legacyRoot . DIRECTORY_SEPARATOR . 'resources' . DIRECTORY_SEPARATOR . 'cxp' . DIRECTORY_SEPARATOR . 'repuestos_tytserv';
$repuestosTemplates = $repuestosRoot . DIRECTORY_SEPARATOR . 'templates';
$outputsDir = $legacyRoot . DIRECTORY_SEPARATOR . 'storage' . DIRECTORY_SEPARATOR . 'outputs';
$uploadsDir = $legacyRoot . DIRECTORY_SEPARATOR . 'storage' . DIRECTORY_SEPARATOR . 'uploads';

return [
    'branding' => [
        'company' => 'Automotores Carlos Larrea',
        'platform' => 'Portal Contable',
        'division' => 'Contabilidad Talleres',
        'tagline' => 'Accesos directos, carga de archivos e historial en un solo lugar.',
        'future_note' => 'Procesos contables',
        'symbol_logo_asset' => 'brand/logo-symbol.jpg',
        'full_logo_asset' => 'brand/logo-full.webp',
    ],
    'home' => [
        'primary_workspace' => 'cxp',
    ],
    'legacy' => [
        'root' => $legacyRoot,
        'public_base_url' => $legacyBaseUrl,
        'download_path' => 'downloads',
    ],
    'storage' => [
        'outputs' => $outputsDir,
        'uploads' => $uploadsDir,
        'jobs' => $legacyRoot . DIRECTORY_SEPARATOR . 'storage' . DIRECTORY_SEPARATOR . 'jobs',
    ],
    'resources' => [
        'acciones' => $accionesRoot,
        'servicios_marcas' => $legacyRoot . DIRECTORY_SEPARATOR . 'resources' . DIRECTORY_SEPARATOR . 'cxp' . DIRECTORY_SEPARATOR . 'servicios_marcas',
        'repuestos_tytserv' => $legacyRoot . DIRECTORY_SEPARATOR . 'resources' . DIRECTORY_SEPARATOR . 'cxp' . DIRECTORY_SEPARATOR . 'repuestos_tytserv',
    ],
    'action_exports_config' => $legacyRoot . DIRECTORY_SEPARATOR . 'config' . DIRECTORY_SEPARATOR . 'cxp' . DIRECTORY_SEPARATOR . 'action_exports.json',
    'workspaces' => [
        'cxp' => [
            'slug' => 'cxp',
            'title' => 'Contabilidad Talleres',
            'summary' => 'Acceso principal a los procesos mensuales de Contabilidad Talleres.',
            'legacy_url' => $legacyBaseUrl . '/cxp',
            'windows' => [
                'libro-compras-aclt',
                'conciliacion-servicios-marcas',
                'facturacion-repuestos-tytserv',
            ],
        ],
        'contabilidad-general' => [
            'slug' => 'contabilidad-general',
            'title' => 'Contabilidad General',
            'summary' => 'Area base creada para futuros procesos y controles de Contabilidad General.',
            'legacy_url' => $legacyBaseUrl . '/contabilidad-general',
            'windows' => [],
            'empty_title' => 'Area creada y lista para crecer.',
            'empty_description' => 'Todavia no hay ventanas ni procesos cargados. Las acciones de esta area se iran registrando despues.',
        ],
    ],
    'windows' => [
        'libro-compras-aclt' => [
            'slug' => 'libro-compras-aclt',
            'title' => 'Libro Compras ACLT',
            'legacy_url' => $legacyBaseUrl . '/cxp/windows/libro-compras-aclt',
            'description' => 'Reune las acciones del libro de compras y su consolidado final.',
            'modules' => ['accion1', 'accion2', 'accion3', 'accion4', 'consolidado-acciones'],
        ],
        'conciliacion-servicios-marcas' => [
            'slug' => 'conciliacion-servicios-marcas',
            'title' => 'Conciliacion Servicios por Marca',
            'legacy_url' => $legacyBaseUrl . '/cxp/windows/conciliacion-servicios-marcas',
            'description' => 'Concilia los archivos del mes y genera una salida lista para descargar por marca.',
            'modules' => ['servicios-marcas'],
        ],
        'facturacion-repuestos-tytserv' => [
            'slug' => 'facturacion-repuestos-tytserv',
            'title' => 'Facturacion Repuestos TYTSERV',
            'legacy_url' => $legacyBaseUrl . '/cxp/windows/facturacion-repuestos-tytserv',
            'description' => 'Procesa ventas y devoluciones por marca para generar el libro final mensual de repuestos.',
            'modules' => ['repuestos-tytserv'],
        ],
    ],
    'modules' => [
        'accion1' => [
            'slug' => 'accion1',
            'title' => 'Accion 1 - Libro Compras Proveedores',
            'legacy_url' => $legacyBaseUrl . '/cxp/modules/accion1',
            'runtime' => 'python-native',
            'future_runtime' => 'python-native',
            'future_processor' => 'python_services/processors/cxp_actions/accion1.py',
            'mode' => 'action',
        ],
        'accion2' => [
            'slug' => 'accion2',
            'title' => 'Accion 2 - Retenciones Proveedores',
            'legacy_url' => $legacyBaseUrl . '/cxp/modules/accion2',
            'runtime' => 'python-native',
            'future_runtime' => 'python-native',
            'future_processor' => 'python_services/processors/cxp_actions/accion2.py',
            'mode' => 'action',
        ],
        'accion3' => [
            'slug' => 'accion3',
            'title' => 'Accion 3 - Mayor Retenciones',
            'legacy_url' => $legacyBaseUrl . '/cxp/modules/accion3',
            'runtime' => 'python-native',
            'future_runtime' => 'python-native',
            'future_processor' => 'python_services/processors/cxp_actions/accion3.py',
            'mode' => 'action',
        ],
        'accion4' => [
            'slug' => 'accion4',
            'title' => 'Accion 4 - Mayor IVA',
            'legacy_url' => $legacyBaseUrl . '/cxp/modules/accion4',
            'runtime' => 'python-native',
            'future_runtime' => 'python-native',
            'future_processor' => 'python_services/processors/cxp_actions/accion4.py',
            'mode' => 'action',
        ],
        'consolidado-acciones' => [
            'slug' => 'consolidado-acciones',
            'title' => 'Consolidado de Acciones',
            'legacy_url' => $legacyBaseUrl . '/cxp/modules/consolidado-acciones',
            'runtime' => 'python-native',
            'future_runtime' => 'python-native',
            'future_processor' => 'python_services/processors/cxp_actions/export_all.py',
            'mode' => 'bundle',
        ],
        'servicios-marcas' => [
            'slug' => 'servicios-marcas',
            'title' => 'Servicios por Marca',
            'legacy_url' => $legacyBaseUrl . '/cxp/modules/servicios-marcas',
            'runtime' => 'laravel+python+excel-com',
            'future_runtime' => 'python-native+excel-com',
            'future_processor' => 'python_services/processors/servicios_marcas/dispatch.py',
            'mode' => 'job',
        ],
        'repuestos-tytserv' => [
            'slug' => 'repuestos-tytserv',
            'title' => 'Repuestos TYTSERV',
            'legacy_url' => $legacyBaseUrl . '/cxp/modules/repuestos-tytserv',
            'runtime' => 'python-native',
            'future_runtime' => 'python-native',
            'future_processor' => 'python_services/processors/repuestos_tytserv/process.py',
            'mode' => 'process',
        ],
    ],
    'repuestos_module' => [
        'python_processor' => 'repuestos_tytserv.process',
        'script_path' => $legacyRoot . DIRECTORY_SEPARATOR . 'scripts' . DIRECTORY_SEPARATOR . 'cxp' . DIRECTORY_SEPARATOR . 'repuestos_tytserv' . DIRECTORY_SEPARATOR . 'process.js',
        'template_dir' => $repuestosTemplates,
        'template_file' => 'FACTURACION REPUESTOS TYTSERV FEBRERO 2026.xlsx',
        'template_path' => $repuestosTemplates . DIRECTORY_SEPARATOR . 'FACTURACION REPUESTOS TYTSERV FEBRERO 2026.xlsx',
        'accepted_extensions' => ['xls', 'xlsx'],
        'output_retention_limit' => 3,
        'upload_retention_limit' => 20,
        'file_fields' => [
            [
                'field' => 'excel_tyt',
                'label' => 'RepLibroVentasGeneral',
                'example_name' => 'RepLibroVentasGeneral',
                'script_flag' => '-InputTyt',
                'brand_key' => 'tyt',
                'brand_label' => 'MATRIZ',
                'source_label' => 'Ventas',
                'summary_key' => 'tyt',
                'summary_label' => 'MATRIZ',
            ],
            [
                'field' => 'excel_nc_tyt',
                'label' => 'RepLibroDevolucionesGeneral',
                'example_name' => 'RepLibroDevolucionesGeneral',
                'script_flag' => '-InputNcTyt',
                'brand_key' => 'tyt',
                'brand_label' => 'MATRIZ',
                'source_label' => 'Devoluciones',
            ],
            [
                'field' => 'excel_peug',
                'label' => 'RepLibroVentasGeneral',
                'example_name' => 'RepLibroVentasGeneral',
                'script_flag' => '-InputPeug',
                'brand_key' => 'peug',
                'brand_label' => 'PEUGEOT',
                'source_label' => 'Ventas',
                'summary_key' => 'peug',
                'summary_label' => 'PEUGEOT',
            ],
            [
                'field' => 'excel_nc_peug',
                'label' => 'RepLibroDevolucionesGeneral',
                'example_name' => 'RepLibroDevolucionesGeneral',
                'script_flag' => '-InputNcPeug',
                'brand_key' => 'peug',
                'brand_label' => 'PEUGEOT',
                'source_label' => 'Devoluciones',
            ],
            [
                'field' => 'excel_chgn',
                'label' => 'RepLibroVentasGeneral',
                'example_name' => 'RepLibroVentasGeneral',
                'script_flag' => '-InputChgn',
                'brand_key' => 'chgn',
                'brand_label' => 'CHANGAN',
                'source_label' => 'Ventas',
                'summary_key' => 'chgn',
                'summary_label' => 'CHANGAN',
            ],
            [
                'field' => 'excel_nc_chgn',
                'label' => 'RepLibroDevolucionesGeneral',
                'example_name' => 'RepLibroDevolucionesGeneral',
                'script_flag' => '-InputNcChgn',
                'brand_key' => 'chgn',
                'brand_label' => 'CHANGAN',
                'source_label' => 'Devoluciones',
            ],
            [
                'field' => 'excel_szk',
                'label' => 'RepLibroVentasGeneral',
                'example_name' => 'RepLibroVentasGeneral',
                'script_flag' => '-InputSzk',
                'brand_key' => 'szk',
                'brand_label' => 'SUZUKI',
                'source_label' => 'Ventas',
                'summary_key' => 'szk',
                'summary_label' => 'SUZUKI',
            ],
            [
                'field' => 'excel_nc_szk',
                'label' => 'RepLibroDevolucionesGeneral',
                'example_name' => 'RepLibroDevolucionesGeneral',
                'script_flag' => '-InputNcSzk',
                'brand_key' => 'szk',
                'brand_label' => 'SUZUKI',
                'source_label' => 'Devoluciones',
            ],
        ],
        'page' => [
            'top_note' => 'Carga y procesamiento mensual por 4 marcas',
            'hero_chip' => 'Flujo mensual',
            'hero_lead' => 'Carga ventas y devoluciones de cada marca para generar un solo libro final del mes.',
            'hero_note' => 'El resultado incluye las hojas operativas necesarias para revision y descarga.',
            'inputs_title' => 'Antes de empezar',
            'retention_tag' => 'Retencion',
            'retention_description' => 'Se conservan solo las ultimas 3 salidas del modulo.',
            'process_title' => 'Cargar archivos del mes',
            'process_description' => 'Sube los 8 archivos del mes: 4 de ventas y 4 de devoluciones.',
            'button_label' => 'Procesar y generar reporte',
            'output_tag' => 'Salida',
            'output_title' => 'storage/outputs',
            'output_description' => 'Prefijo de archivos: repuestos_tytserv_',
            'history_title' => 'Historial reciente',
            'history_empty_title' => 'No hay reportes generados aun.',
            'history_empty_description' => 'La primera ejecucion aparecera aqui.',
        ],
    ],
    'servicios_module' => [
        'python_processor' => 'servicios_marcas.dispatch',
        'template_dir' => $serviciosTemplates,
        'history_limit' => 4,
        'history_scan_limit' => 20,
        'jobs' => [
            'worker_timeout_seconds' => 2700,
            'stale_max_age_seconds' => 3600,
            'queued_timeout_seconds' => 300,
            'cancel_grace_seconds' => 120,
            'dispatch_boot_timeout_seconds' => 20,
        ],
        'hero' => [
            'chip' => 'Proceso mensual',
            'lead' => 'Sube los 2 Excel comunes del mes y los TXT de cada marca. El sistema generara una salida final por marca.',
            'note' => 'Puedes dejar esta pantalla abierta mientras termina el proceso y descargar los resultados al finalizar.',
        ],
        'upload_panel' => [
            'title' => 'Cargar archivos',
            'description' => 'Los 2 Excel son comunes. Los TXT se cargan por marca con REP FACTURACION, NOTA DE CREDITO y MAYOR.',
            'button_label' => 'Procesar y generar plantillas',
            'processing_label' => 'Procesando archivos...',
            'retention_tag' => 'Retencion',
            'retention_title' => '1 archivo por marca',
            'retention_description' => 'La limpieza automatica conserva solo los archivos recientes listos para descargar.',
            'pending_hint' => 'Puedes dejar esta pagina abierta. Se actualizara sola cuando termine el proceso.',
        ],
        'history_panel' => [
            'title' => 'Historial Reciente',
            'description' => 'Se muestra el archivo mas reciente disponible de cada marca.',
            'empty_title' => 'No hay archivos generados aun.',
            'empty_description' => 'La primera ejecucion aparecera aqui.',
        ],
        'stop' => [
            'button_label' => 'Detener proceso activo',
            'confirm_message' => 'Se solicitara detener el proceso activo de esta pantalla.',
            'processing_label' => 'Deteniendo proceso...',
        ],
        'poll' => [
            'interval_ms' => 4000,
            'initial_delay_ms' => 2000,
            'reconnecting_message' => 'Actualizando estado del proceso...',
            'status_error' => 'No se pudo consultar el estado del proceso.',
        ],
        'brands' => [
            ['key' => 'changan', 'label' => 'CHANGAN', 'description' => 'Datos filtrados por marca en su libro operativo.'],
            ['key' => 'peug', 'label' => 'PEUGEOT', 'description' => 'Facturas y notas separadas en la base visible del mes.'],
            ['key' => 'szk', 'label' => 'SUZUKI', 'description' => 'Consolida SUZUKI AMBATO y SUZUKI RIOBAMBA.'],
            ['key' => 'tyt', 'label' => 'MATRIZ', 'description' => 'Respeta el formato mensual definido para MATRIZ.'],
        ],
        'upload_definitions' => [
            'px_file' => [
                'label' => 'PX',
                'example_name' => 'detalle-vtas-xliquidar',
                'accept' => ['xls', 'xlsx'],
                'scope' => 'common',
            ],
            'repventas_file' => [
                'label' => 'REP VENTAS',
                'example_name' => 'RepFacturacionServContabilidad',
                'accept' => ['xls', 'xlsx'],
                'scope' => 'common',
            ],
            'factura_changan_file' => [
                'label' => 'REP FACTURACION CHANGAN',
                'example_name' => 'SERREP_FACTURAS_NAFCHAN',
                'accept' => ['txt'],
                'scope' => 'brand',
                'brand' => 'changan',
            ],
            'nota_changan_file' => [
                'label' => 'NOTA DE CREDITO CHANGAN',
                'example_name' => 'SERREP_NOTACRED_NAFCHAN',
                'accept' => ['txt'],
                'scope' => 'brand',
                'brand' => 'changan',
            ],
            'mayor_changan_file' => [
                'label' => 'MAYOR VENTAS CHANGAN',
                'example_name' => 'CON_MAYORGEN2CHAN',
                'accept' => ['txt'],
                'scope' => 'brand',
                'brand' => 'changan',
            ],
            'factura_peug_file' => [
                'label' => 'REP FACTURACION PEUGEOT',
                'example_name' => 'SERREP_FACTURAS_NAFPEU',
                'accept' => ['txt'],
                'scope' => 'brand',
                'brand' => 'peug',
            ],
            'nota_peug_file' => [
                'label' => 'NOTA DE CREDITO PEUGEOT',
                'example_name' => 'SERREP_NOTACRED_NAFPEU',
                'accept' => ['txt'],
                'scope' => 'brand',
                'brand' => 'peug',
            ],
            'mayor_peug_file' => [
                'label' => 'MAYOR VENTAS PEUGEOT',
                'example_name' => 'CON_MAYORGEN2PEU',
                'accept' => ['txt'],
                'scope' => 'brand',
                'brand' => 'peug',
            ],
            'factura_szk_file' => [
                'label' => 'REP FACTURACION SUZUKI',
                'example_name' => 'SERREP_FACTURAS_NAFSUZAMBYRIO',
                'accept' => ['txt'],
                'scope' => 'brand',
                'brand' => 'szk',
            ],
            'nota_szk_file' => [
                'label' => 'NOTA DE CREDITO SUZUKI',
                'example_name' => 'SERREP_NOTACRED_NAFSUZAMBYRI',
                'accept' => ['txt'],
                'scope' => 'brand',
                'brand' => 'szk',
            ],
            'mayor_szk_file' => [
                'label' => 'MAYOR VENTAS SUZUKI',
                'example_name' => 'CON_MAYORGEN2SUZ',
                'accept' => ['txt'],
                'scope' => 'brand',
                'brand' => 'szk',
            ],
            'factura_tyt_file' => [
                'label' => 'REP FACTURACION MATRIZ',
                'example_name' => 'SERREP_FACTURAS_NAFTOY',
                'accept' => ['txt'],
                'scope' => 'brand',
                'brand' => 'tyt',
            ],
            'nota_tyt_file' => [
                'label' => 'NOTA DE CREDITO MATRIZ',
                'example_name' => 'SERREP_NOTACRED_NAFTOY',
                'accept' => ['txt'],
                'scope' => 'brand',
                'brand' => 'tyt',
            ],
            'mayor_tyt_file' => [
                'label' => 'MAYOR VENTAS MATRIZ',
                'example_name' => 'CON_MAYORGEN2TOY',
                'accept' => ['txt'],
                'scope' => 'brand',
                'brand' => 'tyt',
            ],
        ],
        'output_config' => [
            'changan' => ['label' => 'CHANGAN', 'prefix' => 'servicios_changan_'],
            'peug' => ['label' => 'PEUGEOT', 'prefix' => 'servicios_peug_'],
            'szk' => ['label' => 'SUZUKI', 'prefix' => 'servicios_szk_'],
            'tyt' => ['label' => 'MATRIZ', 'prefix' => 'servicios_tyt_'],
        ],
    ],
    'action_modules' => [
        'accion1' => [
            'action_key' => 'accion1',
            'execution_driver' => 'python',
            'python_processor' => 'cxp_actions.accion1',
            'upload_field' => 'source_files',
            'upload_label' => 'Archivo PDF de proveedores',
            'example_name' => 'CXPREP_docproveedor',
            'accept' => '.pdf,application/pdf',
            'multiple' => false,
            'accepted_extensions' => ['pdf'],
            'script_path' => $legacyRoot . DIRECTORY_SEPARATOR . 'run_bot.js',
            'template_path' => $accionesTemplates . DIRECTORY_SEPARATOR . 'EJEMPLODECOMOQUEDARIA.xlsx',
            'output_suffix' => '_resultado.xlsx',
            'command_mode' => 'positional_action1',
            'generated_path_prefix' => 'Excel generado (una sola hoja):',
            'ignore_console_prefixes' => ['Auditoria JSON:', 'PDF leido:', 'Excel generado (una sola hoja):'],
            'description' => 'Carga el PDF del proveedor y genera el Excel final del libro de compras.',
            'history_title' => 'Historial reciente de Accion 1',
        ],
        'accion2' => [
            'action_key' => 'accion2',
            'execution_driver' => 'python',
            'python_processor' => 'cxp_actions.accion2',
            'upload_field' => 'source_files',
            'upload_label' => 'Archivo TXT de retenciones',
            'example_name' => 'CXPREP_RET_GENERALACCION2',
            'accept' => '.txt,text/plain',
            'multiple' => false,
            'accepted_extensions' => ['txt'],
            'script_path' => $legacyRoot . DIRECTORY_SEPARATOR . 'run_bot_accion2.js',
            'template_path' => $accionesTemplates . DIRECTORY_SEPARATOR . 'ACCION2.xlsx',
            'output_suffix' => '_accion2.xlsx',
            'command_mode' => 'positional_with_template',
            'generated_path_prefix' => 'Excel generado (una sola hoja):',
            'ignore_console_prefixes' => ['Auditoria JSON:', 'TXT leido:', 'Excel generado (una sola hoja):'],
            'description' => 'Convierte el TXT de retenciones al Excel RET PROV con formato de plantilla.',
            'history_title' => 'Historial reciente de Accion 2',
        ],
        'accion3' => [
            'action_key' => 'accion3',
            'execution_driver' => 'python',
            'python_processor' => 'cxp_actions.accion3',
            'upload_field' => 'source_files',
            'upload_label' => 'Uno o varios TXT MAYOR GENERAL o un PDF',
            'example_name' => 'CON_MAYORGEN2ACCION3',
            'accept' => '.txt,.pdf,text/plain,application/pdf',
            'multiple' => true,
            'accepted_extensions' => ['txt', 'pdf'],
            'script_path' => $legacyRoot . DIRECTORY_SEPARATOR . 'run_bot_accion3.js',
            'template_path' => $accionesTemplates . DIRECTORY_SEPARATOR . 'MAYOR RET_ACCION3.xlsx',
            'output_suffix' => '_accion3.xlsx',
            'command_mode' => 'flagged_with_template',
            'output_base_strategy' => 'first_safe_base_with_batch_suffix',
            'generated_path_prefix' => 'Excel generado (una sola hoja):',
            'ignore_console_prefixes' => ['Auditoria JSON:', 'Archivo leido:', 'Archivos leidos:', 'Excel generado (una sola hoja):'],
            'description' => 'Consolida uno o varios TXT MAYOR GENERAL o procesa un PDF del mismo reporte para generar el Excel MAYOR RET.',
            'history_title' => 'Historial reciente de Accion 3',
        ],
        'accion4' => [
            'action_key' => 'accion4',
            'execution_driver' => 'python',
            'python_processor' => 'cxp_actions.accion4',
            'upload_field' => 'source_files',
            'upload_label' => 'Archivo TXT MAYOR IVA',
            'example_name' => 'CON_MAYORGEN2IVAACCION4',
            'accept' => '.txt,text/plain',
            'multiple' => false,
            'accepted_extensions' => ['txt'],
            'script_path' => $legacyRoot . DIRECTORY_SEPARATOR . 'run_bot_accion4.js',
            'template_path' => $accionesTemplates . DIRECTORY_SEPARATOR . 'MAYORIVAACCION4.xlsx',
            'output_suffix' => '_accion4.xlsx',
            'command_mode' => 'flagged_with_template',
            'generated_path_prefix' => 'Excel generado (una sola hoja):',
            'ignore_console_prefixes' => ['Auditoria JSON:', 'Archivo leido:', 'Excel generado (una sola hoja):'],
            'description' => 'Genera el Excel MAYOR IVA respetando la estructura del ejemplo manual.',
            'history_title' => 'Historial reciente de Accion 4',
        ],
        'consolidado-acciones' => [
            'action_key' => 'bundle',
            'execution_driver' => 'python',
            'python_processor' => 'cxp_actions.export_all',
            'script_path' => $legacyRoot . DIRECTORY_SEPARATOR . 'run_export_all_actions.js',
            'output_suffix' => '.xlsx',
            'description' => 'Genera un solo Excel con el ultimo archivo disponible de cada accion.',
            'history_title' => 'Historial reciente del consolidado',
        ],
    ],
];
